version: '3.9'
name: localflix
services:
  server:
    container_name: server
    ports:
      - 8080:8080
    environment:
      LF_LIBRARY_LOCATION: /library
      LF_VERSION: 0.1.0
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/app
      - ~/localflix:/library # Map the ~/localflix directory on the host to /library inside the container
